Cyber4All/learning-object-service

package-lock.json, package.json, src/drivers/MongoDriver.ts, src/drivers/express/ExpressResponder.spec.ts, src/drivers/express/ExpressResponder.ts, src/drivers/express/ExpressRouteDriver.ts, src/interactors/LearningObjectInteractor.ts, src/interfaces/DataStore.ts, src/interfaces/Responder.ts, src/tests/MockExpressResponse.ts, tsconfig.json
Dependant on https://github.com/Cyber4All/CLARK-Gateway/pull/9
=> CRUD for children objects

package-lock.json, package.json, src/drivers/MongoDriver.ts
Requires a CART_SERVICE_URI environment variable added to the was config before deployment
=> Implement functionality to clean deleted objects from users carts

package-lock.json, package.json, src/interactors/LearningObjectInteractor.ts
Perform check on ability to toggle on full object not partial
=> Publishing hotfix - Beta 2.6

gulpfile.js, package.json, src/app.ts, src/drivers/MongoDriver.ts, src/drivers/drivers.ts, src/drivers/express/ExpressAdminRouteDriver.ts, src/drivers/express/ExpressDriver.ts, src/drivers/express/ExpressRouteDriver.ts, src/interactors/AdminLearningObjectInteractor.ts, src/interactors/LearningObjectInteractor.ts, src/interactors/interactors.ts, src/interfaces/DataStore.ts, tslint.json
=> Search Hotfix - Beta 1.25

package.json, src/drivers/express/ExpressRouteDriver.ts
Add correct modifier to FileManager param.
=> Upload Hotfix - Beta 2.17

package.json, src/drivers/MongoDriver.ts
Combine text index searching with regex searching for more coverage.
Text indexing would only match full words added Regex for partial matching.
ie.'cyber' would not match 'cybersecurity'
=> Searching hotfix - Beta 2.18

package-lock.json, package.json, src/drivers/MongoDriver.ts
=> Author attribution

package.json, src/drivers/MongoDriver.ts, src/interactors/LearningObjectInteractor.ts
Resolves https://github.com/Cyber4All/learning-object-service/issues/79
=> :sparkles: Inject ids in Learning Objects - 1.0.2

package.json, src/drivers/S3Driver.ts, src/drivers/express/ExpressAuthRouteDriver.ts, src/interactors/LearningObjectInteractor.ts, src/interfaces/FileManager.ts
Add ability to generate pdf on create and update
=> :recyle: Refactor file upload & :sparkles: Add PDF Generation

package-lock.json, package.json, src/interactors/LearningObjectInteractor.ts
Separated upload path and actual path, so that proper structure would be returned
=> Fix bug with folder structure path

package.json, src/drivers/MongoDriver.ts
The query for contributors was using the wrong property to search. User's id is stored in contributors array, but query was searching by user's username.
Fixed by searching by id instead of username.
=> :bug: Fix contributor search

package-lock.json, package.json, src/drivers/MongoDriver.ts, src/interactors/AdminLearningObjectInteractor.ts, src/middleware/whitelist.ts
The env for whitelist checking in development was inconsistent with production. The correct env should be WHITELISTURL, not WHITELISTURLSD.
=> Single File Download hotfix

package-lock.json, package.json, src/drivers/MongoDriver.ts, src/drivers/express/ExpressAuthRouteDriver.ts
Add sentry error handling to single download route
=> add sentry handling

package-lock.json, package.json, src/middleware/whitelist.ts
=> Remove whitelist log

package-lock.json, package.json, src/drivers/express/ExpressRouteDriver.ts, src/interactors/LearningObjectInteractor.ts
Remove cookie check from single file download route
=> remove cookie check from public route

package-lock.json, package.json, src/drivers/MongoDriver.ts, src/drivers/express/ExpressRouteDriver.ts, src/interactors/LearningObjectInteractor.ts, src/routes.ts
Instead of nondescript  "Internal Server Error" message, the server will now respond will simple 404 page with link a to the learning object.
=> :sparkles: Add 404 page for files that do not exist

package-lock.json, package.json, src/drivers/MongoDriver.ts, src/interactors/AdminLearningObjectInteractor.ts
Needed to add status under outcome in order for "change status" to work on the admin dashboard.
=> add status outcome

package-lock.json, package.json, src/drivers/MongoDriver.ts, src/drivers/express/ExpressRouteDriver.ts, src/interactors/LearningObject.interactor.spec.ts, src/interactors/LearningObjectInteractor.ts, src/interfaces/DataStore.ts, test_environment/globalConfig.json
This PR begins to address the ongoing problem of having large interactor functions covering multiple business use cases. Specifically, this PR adds an interactor function specifically for retrieving the objects for a users profile based on the requester's access groups and privileges.
=> Implement route to load user's profile

package-lock.json, package.json, src/interactors/LearningObjectInteractor.ts
This PR fixes the issue where a curator/review would request released objects and objects in the review stage of their collections would be returned.
=> Fix reviewers/curators receiving objects in review when requesting released

package-lock.json, package.json, src/drivers/MongoDriver.ts, src/interactors/LearningObjectInteractor.ts
service throwing a 400 when loading a released learning object
=> Fix fetch for released learning objects

package-lock.json, package.json, src/LearningObjects/LearningObjectRouteHandler.ts
This PR fixes learning objects not being updated because of a parameter mismatch.
=> Fix Learning Object updates failing

package-lock.json, package.json, src/drivers/MongoDriver.ts
This PR fixes an issue with the sort stage of the aggregation not being constructed properly resulting in sort filters not being applied for users with elevated privileges.
=> Fix aggregation sort not being applied

package-lock.json, package.json, src/FileManager/FileInteractor.ts, src/drivers/express/ExpressAuthRouteDriver.ts
This PR adds routes to allow client to request file upload for specific user.
=> Add routes to allow uploading to specific user

package-lock.json, package.json, src/LearningObjects/AuthorizationManager.spec.ts, src/LearningObjects/AuthorizationManager.ts, src/LearningObjects/LearningObjectInteractor.ts, src/LearningObjects/LearningObjectRouteHandler.ts, src/LearningObjects/typings/index.ts, src/drivers/MongoDriver.ts, src/interfaces/DataStore.ts, src/tests/mock-drivers/MockDataStore.ts
This PR exposes a route to add file metadata to a Learning Object.
=> Add route to add file metadata

.circleci/config.yml, package-lock.json, package.json, src/Changelogs/ChangelogDatastore.spec.ts, src/LearningObjectStats/LearningObjectStatsRouteHandler.spec.ts, src/LearningObjects/LearningObjectRouteHandler.spec.ts, src/LearningOutcomes/LearningOutcomeRouteHandler.spec.ts, src/drivers/MongoDriver.spec.ts
Mixup with git refs made it easier to open a new branch than fix the old. This is a re-do of #323.
=> Test improvements fixes

package-lock.json, package.json, src/LearningObjects/Publishing/ReleaseEmails/lambda-gateway-factory.ts
***Purpose of this PR***
Temporarily turn off release notifications
***Changes***
Return an instance of LambdaGatewayStub in production
=> Temporarily disable Learning Object release email notifications

package-lock.json, package.json, src/LearningObjects/Publishing/ReleaseEmails/lambda-gateway-factory.ts
Reverts Cyber4All/learning-object-service#385
***Purpose of this PR***
Enable Learning Object release notifications
=> Revert "Temporarily disable Learning Object release email notifications"

package-lock.json, package.json, src/drivers/express/ExpressDriver.ts
Fix unauthorized error on file downloads
**Changes**
- Move FileManagerModule's router to public
=> Fix unauthorized error on file downloads

package-lock.json, package.json, src/shared/types/learning-object-updates.ts
***Purpose of this PR***
Fix bug where Learning Object collection was not being set correctly in the submission process.
=> Add collection property to Learning Object Updates

package-lock.json, package.json, src/LearningObjectSearch/drivers/LearningObjectDatastore/ElasticSearchLearningObjectDatastore.ts
Fixes search by contributor as a privileged user
Adds contributor metadata properties to searchable text fields
=> Fix search by contributor as privileged user

package-lock.json, package.json, src/drivers/MongoDriver.ts, src/drivers/express/ExpressAuthRouteDriver.ts, src/drivers/express/ExpressRouteDriver.ts, src/interactors/LearningObject.interactor.spec.ts, src/interactors/LearningObjectInteractor.ts
This PR is intended to improve performance in areas causing bottlenecks, such as fetching Learning Objects when downloading.
- Remove calls to load metrics for lists of Learning Objects
- Remove unused aggregation
=> Remove unnecessary network hops to improve performance

package-lock.json, package.json, src/LearningObjects/LearningObjectsModule.ts, src/LearningObjects/gateways/UserGateway/HttpUserGateway.ts, src/LearningObjects/gateways/UserGateway/Routes.ts, src/LearningObjects/gateways/index.ts, src/LearningObjects/interfaces/index.ts
Fixes issue with creating revision due to the request to load user information failing.
- Inject Bearer token in request to get user
- Move `ModuleUserGateway` to `HttpUserGateway`
=> Move ModuleUserGateway to HttpUserGateway and inject Bearer Token

package-lock.json, package.json, src/drivers/MongoDriver.ts
Fixes regex partial matching when invalid characters are passed in.
- Sanitize regex inputs
- Refactor regex match syntax to simplify
=> Add missing regex sanitization

package-lock.json, package.json, src/LearningObjects/Hierarchy/HierarchyInteractor.ts, src/drivers/MongoDriver.ts
Fixes https://github.com/Cyber4All/learning-object-service/issues/444
*Changes in this PR*
- Pass empty array if `accessGroups` are not defined
=> Fix error when accessGroups is undefined

package-lock.json, package.json, src/app.ts
remove the headers timeout and set the keep alive timeout to a higher value
=> change keep alive timeout in app.ts

package-lock.json, package.json, src/LearningObjectSearch/drivers/LearningObjectDatastore/ElasticSearchLearningObjectDatastore.ts
Report elasticsearch errors to sentry
=> add report error to elastic search

package-lock.json, package.json, src/LearningObjects/LearningObjectInteractor.ts, src/drivers/MongoDriver.ts, src/shared/entity/learning-object/error-messages.ts, src/shared/entity/learning-object/learning-object.ts, src/shared/functions/index.ts, src/shared/types/learning-object-document.ts, src/shared/types/learning-object-summary.ts
This PR introduces the notion of the CLARK Universal Identifier (CUID). This property is meant to be shared between the various database documents that make up a Learning Object. While those documents may have different `_id` properties, they will be joined by the CUID.
=> Implement the CLARK Universal Identifier (CUID)

package-lock.json, package.json, src/FileManager/drivers/FileManager/S3FileManager.ts, src/FileManager/interactors/downloadBundle.ts
***Purpose***
This PR updates the error message that is reported to Sentry when streaming files.
=> Improve sentry error message when streaming files

package-lock.json, package.json, src/FileManager/drivers/FileManager/S3FileManager.ts
Reverts Cyber4All/learning-object-service#470
=> Revert "Improve sentry error message when streaming files"

package-lock.json, package.json, src/FileManager/drivers/FileManager/S3FileManager.ts, src/FileManager/interactors/downloadBundle.ts
This PR sets the file path as the error message during file stream
=> Improve file stream error report

package-lock.json, package.json, src/LearningObjectSearch/interactors/searchUsersObjects/searchUsersObjects.ts
=> Fix bug where service throws a 500 when receiving a 404 from User Service

package-lock.json, package.json, src/LearningObjects/LearningObjectInteractor.ts
Removes copying the files array to a releasable object.
=> Remove files from generating a releasable learning object

package-lock.json, package.json, src/shared/MongoDB/HelperFunctions/documentReleasedLearningObject/documentReleasedLearningObject.ts
=> Bring documentOutcome back from the dead

package-lock.json, package.json, src/LearningObjects/LearningObjectInteractor.ts
We were trying to fetch an object at version 0 after we have already deleted it which threw errors in the fetchInternalLearningObjectByCuid function.
=> Fix 404 for deleting a learning Object properly

package-lock.json, package.json, src/shared/functions/index.ts, src/shared/types/learning-object-summary.ts
This PR adds an email property to the Author summary.
=> Send email down with Author summary

package-lock.json, package.json, src/LearningObjectSearch/interactors/searchObjects/searchObjects.ts
This PR only has to be merged if we don't figure out a long term solution by Thursday. This temporary fixes the issue we have with data inconsistency within elasticsearch at the moment.
=> Bandaid for filters in Production

package-lock.json, package.json, src/drivers/express/ExpressDriver.ts
This PR adds an error for unauthenticated users in the FileManagerModule
=> Throw 401 for unauthenticated user

package-lock.json, package.json, src/shared/MongoDB/HelperFunctions/getFileTypesOnObjects/getFileTypesOnObjects.ts
=> Add vimeo filetype

Dockerfile, package-lock.json, package.json, src/drivers/express/ExpressDriver.ts
***Purpose***
This PR grants public access to all file manager endpoints 
***Story***
This PR addresses Clubhouse story https://app.clubhouse.io/clarkcan/story/1919/investigate-issue-with-file-preview-link
=> expose file manager endpoints

package-lock.json, package.json, src/LearningObjects/Hierarchy/HierarchyRouteHandler.ts, src/shared/entity/learning-object/learning-object.ts
This PR addresses the issue with the parents route returning a 404.
=> Make parents route match childrens route
