src/drivers/MongoDriver.ts
src/interactors/LearningObjectInteractor.ts
src/interactors/LibraryInteractor.ts
src/routes.ts

Remove cart clean up logic from MongoDriver and into LearningObject interactor.
MongoDriver should not make requests to external services.

Remove cart clean up logic from MongoDriver

---

src/interactors/LearningObjectInteractor.ts

Word stemmer plugin used in interactor was producing inaccurate results causing the search query to be inaccurate. Word stemming will be handed off to MongoDB exclusively via it's `$text` operator.

Remove Word Stemming in Interactor

---

package.json
src/drivers/MongoDriver.ts
src/interactors/LearningObjectInteractor.ts
src/interfaces/DataStore.ts

This issue was caused by there being race conditions present when concurrently updating a learning object's document in the database. 
Before, the latest copy of a learning object would be fetched from the database so that the interactor could iterate over the array of files and check if the metadata for the file that was just uploaded already existed. ( In the case of a file being overwritten). If the file's metadata existed, the metadata would be updated, else the file is new and its metadata was added to the array of files. The object was then updated in its entirety. Since the file uploads happen in parallel, there were cases where the version of a learning object loaded was no longer up to date, which resulted in replacing the document with a copy that was inconsistent with the …

Fix issue with missing file metadata 

---

package.json
src/drivers/MongoDriver.ts
src/interactors/LearningObjectInteractor.ts
src/interfaces/DataStore.ts

Files downloaded directly from API were improperly name with the file's id instead of their name and extension. Service has been updated to name files with their name and extension concatenated.

:bug: Fix incorrect filename

---

package.json
src/interactors/LearningObjectInteractor.ts
src/routes.ts

**Before**
- Learning objects' Readme PDFs **Description** section printed rich text encoding to the PDF causing PDF format to break.
- Learning objects' Readme PDFs **Notes** would truncate text that had new line characters.
**Fixes**
- **Description** section has been removed from PDF
- **Notes** section splits `notes` by new line character and writes each line to the PDF using one `doc.text` API call per line.

Fix PDF Generation

---

package-lock.json
package.json
src/drivers/express/ExpressAdminRouteDriver.ts
src/drivers/express/ExpressDriver.ts
src/interactors/AdminLearningObjectInteractor.ts

LibraryCommunicator was not being properly injected into the admin route handler.

Fix object search in admin dashboard

---

package-lock.json
package.json
src/LearningObjects/PDFKitDriver.ts
src/middleware/whitelist.ts

The whitelisturl env in production is deformed and node-fetch is reading it as a relative path instead of a full URL. The PR will include a console.log so that we can see exactly what is happening to the string.
This PR also includes the PDF fix for single file downloads

Single download fix

---

package-lock.json
package.json
src/drivers/express/ExpressAuthRouteDriver.ts
src/drivers/express/ExpressDriver.ts
src/drivers/express/ExpressRouteDriver.ts
src/interactors/LearningObjectInteractor.ts

This PR addresses a bug where, when attempting to preview a document using the office live preview URL, the Microsoft API can't access the file due to CLARK's auth check. This PR removes the authentication from the single file download route, making it a public route.

Move single file download route to unauthenticated route driver and remove authentication logic

---

package-lock.json
package.json
src/interactors/LearningObjectInteractor.ts

The route for single file downloads was checking for a "download" restriction on the object. Objects that had the "download" restriction caused the service to throw an "Invalid Access. You do not have download privileges for this file" error. Because the single file download route is now public and we are not checking the whitelist, this check should be removed.

remove download restriction check

---

package.json
src/LearningObjectStats/LearningObjectStatStore.ts
src/LearningObjectStats/LearningObjectStatsInteractor.ts
src/LearningObjectStats/LearningObjectStatsRouteHandler.ts
src/drivers/MongoDriver.ts
src/drivers/express/ExpressRouteDriver.ts
src/interfaces/DataStore.ts

Added a route `/learning-objects/stats` to fetch the following properties about the  learning object collection:
- Downloads
- Saves
- Number of objects by length
This route accepts query parameters for `collection`, `name`, `authorID`, `length`, and `status`.

:sparkles: Add route to fetch Learning Object stats

---

package-lock.json
package.json
src/FileManager/S3Driver.ts
src/assets/filenotfound.ts
src/drivers/express/ExpressRouteDriver.ts
src/interactors/LearningObjectInteractor.ts
src/interfaces/FileManager.ts

Errors in the single file download route were causing the learning object service to crash. The problem was that an error was being thrown in the stream, after it was opened to S3 and being piped to the client. This PR adds a function to send a HEAD request to S3 to verify that the file is accessible before opening the stream.
Additionally, some files did not have a `fileType` set which was resulting in the RouteHandler attempting to set a mimeType of `null`. This is not supported by the express API and was throwing an error.

Fix Single FIle Downloads

---

package-lock.json
package.json
src/FileManager/S3Driver.ts

If the client cancels a download that is in progress, the file stream coming from S3 will throw an error after a timeout window. This PR adds a check to prevent this from being reported.
Resolves #148

Remove error report for canceled downloads

---

src/drivers/express/ExpressRouteDriver.ts

**Issue**
The public route for fetching a user's public Learning Objects passed in an `accessUnpublished` value of `true` allowing other users to see a user's unpublished Learning Objects.
**Solution**
Change `accessUnpublished` to false to restrict access to unpublished Learning Objects.

:bug: Remove public access to unpublished objects

---

package-lock.json
package.json
src/LearningObjectStats/LearningObjectStatStore.ts

Updated mongo query to count all objects with a `published` flag of true and no lock as released, so that `released` stat reflects what is shown on the system.

:bug: Updated released query count

---

package-lock.json
package.json
src/drivers/MongoDriver.ts

This PR fixes issue #194. This issue was caused by the `generateLearningObject` method using LearningObject's setters to construct the object which unintentionally updated objects' date to the current timestamp.
**Solution**
Refactor logic to fetch all data and pass in via the LearningObject's constructor.

:bug: Fix incorrect LearningObject date

---

package-lock.json
package.json
src/drivers/express/ExpressDriver.ts

**Issue**
When an invalid token was handed to the service, an error would be thrown causing the express router to fall through to the first error handling middleware. This middleware happened to be the error handler for authenticated access causing a 401 and `Invalid Access Token` to be sent to the client.
**Solution**
Add error handling middleware after the `processToken` middleware to catch errors and pass execution to the next handler.

Add handler for jwt middleware errors

---

package-lock.json
package.json
src/app.ts

**Issue**
The root was not updated to get the fully constructed `MongoDriver` using the `build` method causing `db` to be undefined.
**Solution**
Use build method at app root.

Use build method to get Datastore

---

package-lock.json
package.json
src/LearningObjectStats/LearningObjectStatStore.ts
src/drivers/MongoDriver.ts

This PR modifies the aggregation query to fetch LearningObject stats to only count objects as released if their status is released.

Update aggregation to count released objects by status

---

package-lock.json
package.json
src/SingleFileDownload/SingleFileDownloadInteractor.ts

Refactoring of the Single File Download business logic was missed when refactoring the the datastore method's function signature.
I have updated it to now use the new function signature. I've set it to request the full object, as I believe that without that the file information does not come through.
Resolves #223

Fix bad function call

---

package-lock.json
package.json
src/drivers/MongoDriver.ts

Faulty logic in the mongo driver's query for reviewers/curators was replacing the search query with the access privileges, thus showing every object a reviewer/curator had access to see on each search.

:ambulance: Fix broken search for reviewers/curators

---

package-lock.json
package.json
src/LearningObjects/PDFKitDriver.ts

**Issue**
Learning Objects with `:` characters in the name would cause the `:` character to be replaced with `/` characters in the PDF file name.
**Solution**
Replace characters that are potentially invalid with `_` characters when constructing the PDF file name.
Closes #146

Remove invalid characters in LO name for PDF filename

---

package-lock.json
package.json
src/drivers/MongoDriver.ts

This PR fixes the issue where `addToReleased` function was throwing errors because the incorrect Mongo API call was being used.
Updated `updateOne` to `replaceOne`

:bug: Fix call to copy object to collection

---

package-lock.json
package.json
src/drivers/MongoDriver.ts

This PR fixes the issue where objects were not properly copied to the released collection.This was caused by a missing `await` statement.
Closes #249

Fix cyclic dependency caused by not awaiting promises

---

package-lock.json
package.json
src/drivers/MongoDriver.ts

This PR fixes the `objects` collection being queried in the `searchReleasedObjects` function instead of the `released-objects` collection.
Thinking this was merged out? :man_shrugging:

:bug: Fix collection pointer in searchReleasedObjects

---

package-lock.json
package.json
src/drivers/MongoDriver.ts
src/drivers/express/ExpressAuthRouteDriver.ts
src/interactors/LearningObject.interactor.spec.ts
src/interactors/LearningObjectInteractor.ts
src/interfaces/DataStore.ts
src/tests/mock-drivers/MockDataStore.ts

This PR fixes the issue where Learning Objects could not be found if released copy's name was different from working copy's name.
Closes #250

Fix Learning Objects not being found if the released copy's name was different from working copy's name

---

package-lock.json
package.json
src/drivers/express/ExpressAuthRouteDriver.ts
src/interactors/AuthorizationManager.ts
src/interactors/LearningObject.interactor.spec.ts
src/interactors/LearningObjectInteractor.ts
src/types/index.ts
src/types/service-token.ts

This PR re-adds the route to fetch a Learning Object's Id (`/learning-objects/:username/:learningObjectName/id`) and refactors authorization logic for this request.
This route is being used by [library-service](https://github.com/Cyber4All/library-service).

Re-add route to fetch Learning Object's Id & Add authorization logic

---

package-lock.json
package.json
src/drivers/express/ExpressRouteDriver.ts

This PR adds backward compatibility for `page` param used for pagination. The service will now accept `currPage` and `page` (the newer version of the parameter) as valid `page` values.
Closes Cyber4All/clark-client#622

Allow `page` and `currPage` as valid page param for backward compatibility

---

package-lock.json
package.json
src/drivers/express/ExpressDriver.ts

This PR fixes an issue where requests to the service would timeout when the requester sent an invalid token. This was caused by the `proccesToken` middleware throwing an error when trying to parse token which resulted in a `JsonWebTokenError`. This case was not being handled in the error handler used after `enforceAuthenticatedAccess` and therefore the service was at the bottom of its handlers and never responded.
This this PR also removed the :hankey: handler used in the `processToken` middleware. By moving the error handler for `enforceAuthenticatedAccess` inside of `use` statement, errors from `proccessToken` no longer bubble out to the handler that responds with a 401. 
We should update this in the rest of our services that are using this pattern as well.
Closes #235

Fix request timeout when token is invalid

---

package-lock.json
package.json
src/drivers/express/ExpressDriver.ts
src/middleware/authenticated-access.ts
src/middleware/index.ts
src/middleware/process-token.ts

This PR fixes a bug introduced in #265 that caused public routes to send a `401` when a user had an invalid token.
These issues were resolved by creating an error handler for the `proccessToken` middleware and moving the error handling for `enforceAuthenticatedAccess` inside of the middleware.

Fix invalid access on public routes

---

package-lock.json
package.json
src/drivers/MongoDriver.ts

This PR fixes the issue where objects added to the `released-objects` collection would have their `children` property set to an empty array. This issue was caused by the Datastore not setting the children property of a LearningObject when fetching the object.
**Solution**
Map the record's `children` property to LearningObjects with just the `id` property.

Fix children array being copied to released-objects as an empty array

---

package-lock.json
package.json
src/LearningObjects/LearningObjectInteractor.ts
src/drivers/MongoDriver.ts

This PR fixes the issue introduced in #276 where child objects would throw validation errors because they were instantiated with just the `id` property and no valid name.
Additionally, this PR replaces the mapping of `id` to Learning Object outbound with a mapping from `childIds` to LearningObject only when Learning Objects are released.

Remove outbound mapping of id to partial Learning Object

---

package-lock.json
package.json
src/drivers/express/ExpressRouteDriver.ts
src/interactors/LearningObjectInteractor.ts

Removes bypass logic when retrieving learning object data to display in order to display the correct status code for a given learning object.
Closes #274

Remove bypass logic to display correct status code

---

package-lock.json
package.json
src/interactors/LearningObjectInteractor.ts

This PR refactors the error handling logic on `LearningObjectInteractor.ts` to use the `handleError` function and adds better reporting.
Closes #263

Refactor interactor level error handling into a function

---

package-lock.json
package.json

This PR fixes all security issues that were being flagged by npm audit. This is done through the gulp upgrade in #283, upgrading Jest, and removing the unused gulp-watch dependency.
(This is a re-opening of #290 - I had to do some tomfoolery with rebasing to get the dependency trees to sync up)

Fix NPM Audit Issues

---

package-lock.json
package.json
src/interactors/LearningObjectInteractor.ts

Passing the `username` instead of the `authorId` was causing service failure when setting or removing child Learning Objects.

Fix Internal Server Error on Child Modification

---

gulpfile.js
package-lock.json
package.json
src/LearningObjects/Hierarchy/HierarchyInteractor.ts
src/LearningObjects/Hierarchy/HierarchyRouteHandler.ts
src/drivers/MongoDriver.ts
src/drivers/express/ExpressRouteDriver.ts
src/interactors/LearningObjectInteractor.ts
src/interfaces/DataStore.ts

**This is still a work in progress**. I would like to get a review of the scenarios described below before they are fully implemented in code. Thanks!
This PR updates the fetchParentObjects method in the datastore to query the released objects collection when that parameter is specified. Previously, there was an optional property declared in the function signature, but it was not being used inside the function.
The following scenarios use blue nodes and edges to convey public access, and black nodes/edges to convey privileged access.
In this situation, regular users will only see the released child object as a stand-alone Learning Object. Privileged users (such as editors, admins, reviewers, curators) will be able to see that the Learning Object is included in parent objects which happen …

Fix Permission Issues on Parent Learning Objects

---

package-lock.json
package.json
src/drivers/express/ExpressRouteDriver.ts

The client was sending `standardOutcomes` as a query property, while the server was expecting `standardOutcomeIDs`. In the same fashion that the page and limit properties are transformed by the route handler, I've added a transform step for this property as well.
Closes #281

Fix cannot filter search by Standard Outcomes

---

package-lock.json
package.json
src/LearningObjects/LearningObjectRouteHandler.ts

This PR addresses an issue where the route to fetch a Learning Object's children responds with an array of fully-constructed Learning Objects instead of a plain JS object.
Requires Cyber4All/clark-client#767

Update route to fetch children to send back plain objects instead of constructed Learning Objects

---

package-lock.json
package.json
src/LearningObjects/LearningObjectInteractor.ts

This PR adds the missing learning object file generation. The `loFile` var set to null and never updated.

Fix missing LoFile generation

---

package-lock.json
package.json
src/interactors/LearningObjectInteractor.ts

This PR updates the service to send full child Learning Objects when the parent Learning Object is requested.
This hotfix is in response to downloads failing for Learning Objects with children.

Send full child Learning Objects when requesting a parent Learning Object

---

package-lock.json
package.json
src/LearningObjectSubmission/SubmissionDatastore.ts
src/LearningObjectSubmission/SubmissionInteractor.ts

This PR removes a check in the `cancelSubmission` function to allow for unrecorded submissions to be canceled.

Allow cancellation of unrecorded submissions

---

package-lock.json
package.json
src/entity/learning-object/learning-object.ts

This PR remove Learning Object's internal call to update the `date` property when a property is modified. This internal call led to Learning Objects being returned with dates that were inconsistent from what was stored in the Datastore.

Remove internal call to update date causing date to be inconsistent

---

package-lock.json
package.json
src/LearningObjects/LearningObjectInteractor.ts
src/LearningObjects/LearningObjectRouteHandler.ts
src/LearningObjects/typings/index.ts
src/drivers/MongoDriver.ts

This PR updates the POST route for `/materials/files` to allow client to add metadata for multiple files with a single request.

Allow addition of multiple file meta

---

package-lock.json
package.json
src/app.ts
src/drivers/MongoDriver.ts
src/shared/Mongo/MongoConnector.ts
src/shared/interfaces/DataStore.ts

This PR takes the pattern of using a Singleton to hold an instance of `MongoClient` that independent modules within the service can share. This was introduced in other services, however there is a slight tweak here.
In order to prevent refactoring of the current `MongoDriver` and keep tests green, I still have the `MongoDriver` run its build method as normal in the `app.ts`. In that build method (this is to keep tests passing) I added a small conditional that if the `MongoConnector` hasn't opened its connection yet, the `MongoDriver` will ask it to do so - then proceed as normal.
I have left FIXMEs in the code on the areas that we should make sure we go back and update after we've continued down the road of refactoring.

Create Singleton Mongo Connection Host

---

package-lock.json
package.json
src/drivers/express/middleware/authenticated-access.ts
src/drivers/express/middleware/process-token.ts

This PR addresses story #153
https://app.clubhouse.io/clarkcan/story/153/remove-authorization-error-reports
The purpose of this PR is to prevent error reporting to Sentry in the case of an invalid token. 
When replicating the error, I found that both `UnauthorizedError` and `JsonWebTokenError` were being thrown when attempting to access the service with an invalid token. I simply added both of these to the conditional. If the produced error does not match either of these types, the middleware reports the error to Sentry. 
This needs to be replicated in all services before resolving the clubhouse story.

Remove Authorization Error Reports

---

package-lock.json
package.json
src/LearningOutcomes/LearningOutcomeRouteHandler.spec.ts
src/LearningOutcomes/LearningOutcomeRouteHandler.ts

This PR fixes an issue where the service would send back a `200` status code, meaning a response body was present, when the status code should have in fact been a `204` status code to indicate no response body is attached.
This fix is in relation to the builder showing error messages when deleting outcomes even though the request was successful. Since the service sent back a `200` the `HttpClient` module would try and parse the body as JSON which threw client errors because no response body existed. Sending back a `204` tells the client there is no response body, so the `HttpClient` module does not attempt to parse it.

Use correct status code when not sending back response body

---

package-lock.json
package.json
src/LearningObjects/LearningObjectRouteHandler.spec.ts

This PR adds test cases to assert that when a Learning Object update request is made by an editor or an admin with `status: released` included, the service responds with a 200 OK.

Test Updates that Release Learning Objects

---

package-lock.json
package.json
src/LearningObjects/LearningObjectInteractor.ts
src/LearningObjects/Publishing/ElasticMongoReleaseRequestDuplicator.ts
src/LearningObjects/Publishing/ElasticSearchPublishingGateway.ts
src/LearningObjects/Publishing/ReleaseRequestDuplicator.ts
src/LearningObjects/Publishing/index.ts
src/LearningObjects/Publishing/interactor.ts

This PR moves the logic of publishing a LearningObject (aka "releasing") to its own module, rather than including it inside of the existing `LearningObjectInteractor` and `MongoDriver`.
The Publishing module exports an anonymous function that instantiates a new `ReleaseRequestDuplicator` (I'm not sold on the name here, so any suggestions are welcome) and replaces the `dataStore` provided to the interactor function, `releaseLearningObject`, with an instance of this class instead.
Then internally, the `ReleaseRequestDuplicator` makes a request to index the Learning Object into ElasticSearch before proceeding as normal to call `addToReleased` on the `MongoDriver` that is hidden behind service-wide `DataStore` interface.
I chose *Publishing* module based on a conversation we had about Domain …

Create Publishing Module

---

package-lock.json
package.json
src/LearningObjectSubmission/SubmissionInteractor.ts

This PR adds a catch block that transforms errors when instantiating a `SubmittableLearningObject` to `ResourceErrors` to avoid sending back a 500 error for a bad submission request.

Catch and handle EntityErrors on Submission

---

package-lock.json
package.json
src/shared/errors.ts

This PR adds the Forbidden error type as a response, allowing our service to differentiate between "I do not have your credentials" and "I know who you are, but you can't do this".

Add Forbidden Error Response

---

package-lock.json
package.json
src/LearningObjectSubmission/SubmissionInteractor.spec.ts

This PR removes tests that are wrongfully passing due to bad logic in the tests or poorly configured test environment conditions.
After talking with @nvisal1, we also realized that these tests are make assertions about the helper functions they use, not the logic they implement, and therefore should be rewritten. This PR only removes the bad tests, and future work with our test environment will go back to implement new, better tests.

Remove false positive tests

---

package-lock.json
package.json
src/LearningObjectSearch/Interactor.ts
src/LearningObjectSearch/drivers/LearningObjectDatastore/ElasticSearchLearningObjectDatastore.ts
src/LearningObjectSearch/typings/query.ts

Fixes issue where `guidelines` and `standardOutcomeIDs` filters were not being applied to the query within`ElasticSearchLearningObjectDatastore`. 
**Approach**
These filters are re-mapped within the `getQueryFilters` function to match the structure of the documents within the ElasticSearch index.

Handle `guidelines` and `standardOutcomeIDs` filters

---

package-lock.json
package.json
src/LearningObjectSearch/drivers/LearningObjectDatastore/ElasticSearchLearningObjectDatastore.ts
src/LearningObjectSearch/typings/index.ts

Defines and enforces `LearningObjectSummary` contract for search request on Learning Objects. This type includes the minimal set of properties needed to provide clients information about a Learning Object, and to fetch more information about a Learning Object.

Update search response payload to `LearningObjectSummary`

---

package-lock.json
package.json
src/LearningObjectSearch/drivers/LearningObjectDatastore/ElasticSearchLearningObjectDatastore.ts
src/LearningObjectSearch/typings/elastic-search.ts

Extends search capabilities by added prefix phrase match stage on `outcomes.text` field.
Co-authored-by: David Nsoesie <davidnsoesie1@gmail.com>

Perform prefix phrase match on outcome text

---

package-lock.json
package.json
src/LearningObjectSearch/drivers/LearningObjectDatastore/ElasticSearchLearningObjectDatastore.ts
src/LearningObjectSearch/typings/elastic-search.ts

Add stage to handle duplicate Learning Objects (object with the same `id`) in Elastic Search results.
**Approach**
Add aggregation stage to ElasticSearch query to group results into buckets by `id`, sort bucket items by `revision` in ascending order and return the first element in the bucket to get the Learning Object that is furthest along in the revision pipeline.

Implement aggregation to filter duplicate Learning Objects

---

package-lock.json
package.json
src/LearningObjects/LearningObjectInteractor.ts
src/drivers/MongoDriver.ts
src/shared/entity/learning-object/learning-object.ts
src/shared/types/learning-object-document.ts

This PR adds the `revision` property to Learning Objects and tags Learning Objects with a revision number of `0` when they are first created.

Tag Learning Objects with revision 0 when created

---

package-lock.json
package.json
src/LearningObjectSearch/typings/index.ts
src/shared/types/index.ts
src/shared/types/learning-object-summary.ts

This PR moves `LearningObjectSummary` types to shared.

Move LearningObjectSummary types to shared

---

package-lock.json
package.json
src/LearningObjectSearch/drivers/LearningObjectDatastore/ElasticSearchLearningObjectDatastore.ts

This PR fixes ElasticSearch results only returning objects in collection for privileged users.

Fix search results only returning objects in collection for privileged users

---

package-lock.json
package.json
src/FileManager/FileInteractor.ts
src/FileManager/FileManagerAdapter.ts
src/FileMetadata/interfaces/FileManagerGateway.ts
src/LearningObjects/Publishing/ModuleFileManagerGateway.ts
src/app.ts

***Purpose of this PR***
The Publishing module needs the ability to request that a file be uploaded to a Learning Object when it is released. This will allow us to upload the bundled files and the meta.json file.
***Changes***
- Create a `FileModuleAdapter` that exposes `FileInteractor` functions. 
- Create a 'ModuleFileModuleGateway` so the publishing module can access the `FileModuleAdapter`
- Create a `FileModuleGateway` abstract class for the `ModuleFileModuleGateway`
- Initialize the `FileModuleAdapter` singleton instance in `app.ts`

Expose uploadFile function through FileManager Adapter

---

.vscode/launch.json
package-lock.json
package.json

This PR adds two launch scripts from running Jest with VS Code's built in debugger. It was a lot of help with my work on #392, so I figured I'd share.

Add Launch Scripts for Jest in VS Code

---

package-lock.json
package.json
src/LearningObjects/Publishing/interactor.ts

This PR adds a new publishing artifact, `meta.json`. This file contains all metadata for a Learning Object at the time of publishing a revision, so that we do not have to store data for old revisions in the database.

Write Learning Object Meta to Storage

---

package-lock.json
package.json
src/LearningObjects/LearningObjectInteractor.ts

Fixes parent Learning Object files being set as the child Learning Objects' files. 
- Fix incorrect parameter being passed when fetching files for child Learning Objects
- Temporarily add materials to children
Materials are added to children temporarily because right now the service responds with the `children` property being "summaries" which don't have defined values for`materials`. This breaks the downloads for Learning Objects with children, because the children don't have `materials.pdf` defined causing errors when trying to fetch their READMEs.
This is a temporary fix as we work to have library service fetch full child objects individually.

Fix parent files being linked to child Learning Objects

---

package-lock.json
package.json
src/FileMetadata/Interactor.ts

Fixes error propagation when validating file metadata.
**Changes**
- Convert `forEach` loop to `for of` loop to allow error to bubble up.

Convert forEach to for of to allow error to propagate

---

package-lock.json
package.json
src/drivers/MongoDriver.ts
src/interactors/LearningObjectInteractor.ts

Fixes issue with searching by guidelines for non-privileged users
Updates search methods in `MongoDrirver` to match guidelines to outcomes to Learning Objects by id.
Update search on outcomes to search by id based on matched outcomes.

Fix search by guidelines for non-privileged users

---

package-lock.json
package.json
src/LearningObjectSubmission/interactors/submitForReview.ts
src/LearningObjects/LearningObjectInteractor.ts
src/drivers/MongoDriver.ts
src/shared/interfaces/DataStore.ts
src/tests/mock-drivers/MockDataStore.ts

Fix issues with releasing Learning Objects with children Learning Objects.
- Create `loadWorkingParentsReleasedChildObjects` function to recursively load the fully qualified released child Learning Objects of a working Learning Object.
This populates the child Learning Objects with all the data needed for the Learning Objects to be bundled and released including all material metadata.
- Update `verifySubmittable` to only validate top level Learning Object that is being submitted is submittable.

Get fully qualified children Learning Objects when releasing

---

package-lock.json
package.json
src/FileMetadata/FileMetadataModule.ts
src/FileMetadata/Interactor.ts
src/FileMetadata/gateways/LearningObjectGateway/ModuleLearningObjectGateway.ts
src/FileMetadata/interfaces/LearningObjectGateway.ts
src/LearningObjects/LearningObjectInteractor.ts
src/LearningObjects/gateways/FileMetadataGateway/ModuleFileMetadataGateway.ts
src/LearningObjects/gateways/FileMetadataGateway/StubFileMetadataGateway.ts
src/LearningObjects/interfaces/FileMetadataGateway.ts
src/shared/entity/learning-object/learning-object.ts
src/shared/types/learning-object-document.ts

Fix inconsistencies in file urls and address issue documented in story https://app.clubhouse.io/clarkcan/story/836/no-preview-of-material-available-while-in-material-upload-dashboard-editorial-mode
- Add function to generate file preview url and return in response when fetching materials, files, and full Learning Objects

Generate previewUrls for files and return in response

---

package-lock.json
package.json
src/shared/Mongo/MongoConnector.ts

Updates Mongo connect error handling to allow the error to be properly reported to sentry. Additionally, this modifies Mongo connection options to clean up warnings from logs and remove redundant retry limit.
- Remove wrapping error in rejected promise
- Use new url parser to remove Mongo warnings from logs
- Remove retry limit (Default was already set at 30).

Update Mongo connection error handling

---

package-lock.json
package.json
src/app.ts

This PR is in response to service failures causing 502 Bad Gateway and 504 Gateway Timeout errors. In attempt to fix this issue based on a suggestion in [this](https://adamcrowder.net/posts/node-express-api-and-aws-alb-502/) article, this PR allows the service's server's keep alive timeout widow to be configured.
- Allows Express server's keep alive time out to be configured by an env variable

Add configurable keep alive timeout

---

package-lock.json
package.json
src/drivers/MongoDriver.ts
src/shared/entity/learning-object/learning-object.ts

This PR fixes the issue where Learning Objects would not be returned when applying the status filter of `released` if the Learning Object existed in both the `objects` collection and `released-objects` collection and had different statuses.
Status filter match stage is applied after initial match stage and creation of the super set in order to avoid filtering out Learning Objects in the released collection.

Fix status filtering when searching all Learning Objects

---

package-lock.json
package.json
src/LearningObjects/Hierarchy/HierarchyRouteHandler.ts

The datastore is returning full `LearningObjects`, so this PR puts the mapping stage back in the route handler.

Fix Details Page Not Displaying Parents' Names

---

package-lock.json
package.json
src/LearningObjects/Hierarchy/HierarchyRouteHandler.ts

The datastore is currently returning a full Learning Object even when it shouldn't (see #438). This PR adds typecasting in to the route handler that is dealing with this so that `tsc` can run without errors. This restores the `npm start` command.

Fix TSLint Errors

---

package-lock.json
package.json
src/LearningObjectSearch/adapters/ExpressHttpAdapter.ts
src/interactors/LearningObjectInteractor.ts

This PR directs all user traffic to the Elastic search index, expect in the case where an author is searching/viewing objects in their dashboard.

Point search traffic to Elastic

---

package-lock.json
package.json
src/LearningObjectSubmission/gateways/FileMetadataGateway/ModuleFileMetadataGateway.ts
src/LearningObjectSubmission/interactors/submitForReview.ts
src/LearningObjectSubmission/interfaces/FileMetadataGateway.ts
src/LearningObjects/LearningObjectInteractor.ts
src/LearningObjects/adapters/LearningObjectAdapter.ts
src/drivers/express/ExpressAuthRouteDriver.ts

***Purpose***
Populate submission readme files with file metadata
***Implementation***
Use the file metadata gateway in the Learning Objects module interactor to fetch files before readme generation
***Story***
This story responds to Clubhouse story https://app.clubhouse.io/clarkcan/story/1047/fix-bug-where-submission-readme-files-were-not-populated-with-files

Fix bug where submission ReadMe files are not populated with files

---

package-lock.json
package.json
src/LearningObjects/LearningObjectInteractor.ts
src/LearningObjects/adapters/LearningObjectRouteHandler.ts
src/shared/entity/learning-object/learning-object.ts
src/shared/functions/index.ts
src/shared/types/learning-object-summary.ts

This PR introduces a `resourceUris` property on Learning Objects returned from the `/learning-objects/:authorUsername/:learningObjectName` route. It can contain an object where each key corresponds to a property on the Learning Object and the value for each key is a URI for fetching that property. 
This will enable to details page (and other areas of the application as this pattern permeates through the system) to handle outages more gracefully, load different pieces of a single view asynchronously, and stop over-fetching data.
**Sample Response**

Add URI's to Learning Objects

---

package-lock.json
package.json
src/FileManager/adapters/ExpressHttpAdapter.ts

***Purpose***
This PR adds functionality to the /bundle route to interpret the presence of a revision query string and translate it to a boolean. This allows the client to use a more restful route convention.

Convert Revision Query String to boolean

---

package-lock.json
package.json
src/FileMetadata/Interactor.ts

This PR removes the zero-byte file check since it throws errors after the uploads complete and is not something that is necessarily indicative of a corrupted file.

Remove zero byte file check

---

package-lock.json
package.json
src/FileManager/adapters/ExpressHttpAdapter.ts
src/FileManager/interactors/downloadBundle.ts
src/LearningObjects/Publishing/interactor.ts

***Purpose***
Currently, every download is streamed to the client with a filename of `bundle.zip`. This is confusing when downloading multiple Learning Objects. This PR changes the name of the .zip file to Learning Object Name.zip before it is streamed to the client. 
As of yesterday, bundles are stored internally as CUID.zip. This change allows us to avoid collisions with user file names.
- This PR points to those newly named bundles. 
- The release process was also updated to generate bundles with the name CUID.zip
***Implementation***
In order to dynamically change file names during the download process, this header was added
`res.header('Content-Disposition', attachment; filename="${req.params.learningObjectName}.zip");`
***Story***
Clubhouse story …

Stream Bundle with Learning Object Name

---

package-lock.json
package.json
src/FileManager/drivers/FileManager/S3FileManager.ts
src/LearningOutcomes/LearningOutcomeRouteHandler.ts
src/shared/entity/learning-object/learning-object.ts

This PR does two things:
1) Fixes a bug where Learning Outcomes are returned as constructed instances of LearningOutcome instead of as plain JS objects
2) Fixes a bug where materials cannot be fetched from the URI if the object is not released.

Fix bugs related to URIs in entity

---

package-lock.json
package.json
src/shared/MongoDB/HelperFunctions/documentReleasedLearningObject/documentReleasedLearningObject.ts

Update documentReleasedObject to use the pattern used for documentObject so that sentry doesn't throw any cannot find function errors.

Mimic call structure from document learning objects

---

package-lock.json
package.json
src/LearningObjects/LearningObjectInteractor.ts
src/LearningObjects/adapters/LearningObjectRouteHandler.ts
src/drivers/MongoDriver.ts
src/shared/MongoDB/HelperFunctions/generateLearningObject/generateLearningObject.ts
src/shared/entity/learning-object/learning-object.ts
src/shared/interfaces/DataStore.ts
src/tests/mock-drivers/MockDataStore.ts

This PR introduces a route to fetch a Learning Object by CUID and Version number. It's backwards compatible with the `/users/:username/learning-objects/:id` route. This PR also changes the LearningObject constructor function to take any object instead of only a `Partial<LearningObject>`

Implement route to fetch versions of a Learning Object CUID and version number

---

src/FileManager/drivers/LearningObjectDownloads/learningObjectLibraryDownload.ts
src/FileManager/interactors/downloadBundle.ts
src/drivers/MongoDriver.ts
src/shared/entity/index.ts
src/shared/entity/libraryItem/libraryItem.ts

The purpose of this PR is to move the functionality of appending the downloaded boolean on the documents in a users library to Learning Object Service. This is a temporary fix until https://app.clubhouse.io/clarkcan/story/1328/update-method-of-storage-of-download-count is completed. 
I created a "Mongo helper" function that took the existing logic from library service to append the downloaded boolean to the documents in the users library. I went with this because this is only a temporary fix and the file can be removed since the function is only being used in one place.

Fix Downloads Counter

---

package-lock.json
package.json
src/LearningObjects/LearningObjectInteractor.ts
src/LearningObjects/adapters/LearningObjectRouteHandler.ts

If the requester is undefined this route currently throws a 500 because the user can't be authenticated for unreleased learning objects. The details just spins and does not handle the error correctly.

Stop from sending 500 for unauthenticated 
